name: hybreed
favicon: null
layout_spectrum: 0.053329833783209324
typography_spectrum: 0.5568560271058232
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.5
  lightness: 0.43695038883015513
  saturation: 0.23603860707953572
  rhythmicContrast: 0.24800757342018187
purpose: []
